// Shared function to send scripts to n8n webhook

const N8N_WEBHOOK_URL =
	process.env.N8N_WEBHOOK_URL ||
	'https://n8n.srv1088518.hstgr.cloud/webhook/c098efaf-0689-4d48-ad8b-5774c30e151c';

export interface ConceptScript {
	conceptName: string;
	script: string;
	wordCount?: number;
	estimatedDuration?: string;
	visualCues?: string[];
}

export interface ScriptsPayload {
	scripts: ConceptScript[];
}

export interface N8NResult {
	conceptName: string;
	success: boolean;
	response?: any;
	error?: string;
}

/**
 * Sends scripts generated by Mastra agent to n8n webhook
 * @param scripts - Array of scripts from Mastra agent
 * @returns Array of results for each script
 */
export async function sendScriptsToN8N(
	scripts: ConceptScript[],
): Promise<N8NResult[]> {
	const results: N8NResult[] = [];

	// Log that we're using scripts from Mastra agent
	console.log(
		`Processing ${scripts.length} scripts from Mastra agent for n8n`,
	);

	// Send each script to n8n (using the exact scripts generated by Mastra agent)
	for (const scriptData of scripts) {
		try {
			// Verify we have the required fields from Mastra agent
			if (!scriptData.conceptName || !scriptData.script) {
				throw new Error(
					'Invalid script data: missing conceptName or script field from Mastra agent',
				);
			}

			// Log the script data from Mastra agent
			console.log(
				`Processing Mastra-generated script for concept: "${scriptData.conceptName}"`,
			);
			console.log('Script data from agent:', {
				conceptName: scriptData.conceptName,
				script: scriptData.script,
				wordCount: scriptData.wordCount,
				estimatedDuration: scriptData.estimatedDuration,
				visualCues: scriptData.visualCues,
			});

			// Format the script data into n8n's expected prompt format
			// n8n's AI Agent expects a user prompt that will generate:
			// 1. A detailed video prompt (900-1800 chars)
			// 2. A short caption with hashtags (max 12 words)
			// 3. A YouTube Short title (max 100 chars)
			// 4. A description (up to 2000 chars)
			const visualCuesText = scriptData.visualCues
				? scriptData.visualCues.join(', ')
				: '';

			const n8nPrompt = `<user>
Generate a fast, surreal cinematic video idea based on this educational concept script.

Concept: ${scriptData.conceptName}
Script: ${scriptData.script}
${visualCuesText ? `Visual Cues: ${visualCuesText}` : ''}

Provide:
1. A highly detailed video prompt (min. 900 – max. 1800 characters) that visualizes this educational concept in a surreal, cinematic way.
2. A short hypnotic caption (max. 12 words) with hashtags.
3. A YouTube Short title (max. 100 characters).
4. A description (humorous, keyword-rich, up to 2000 characters).
</user>`;

			// Use the exact script data from Mastra agent
			const payload = {
				conceptName: scriptData.conceptName,
				script: scriptData.script,
				wordCount: scriptData.wordCount,
				estimatedDuration: scriptData.estimatedDuration,
				visualCues: scriptData.visualCues,
				// Include the formatted prompt for n8n's AI Agent
				text: n8nPrompt,
			};

			console.log(
				`Sending script "${scriptData.conceptName}" to n8n webhook: ${N8N_WEBHOOK_URL}`,
			);

			const response = await fetch(N8N_WEBHOOK_URL, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify(payload),
			});

			if (!response.ok) {
				const errorText = await response.text().catch(() => '');
				console.error(
					`n8n webhook error for "${scriptData.conceptName}":`,
					response.status,
					response.statusText,
					errorText,
				);
				throw new Error(
					`n8n webhook returned ${response.status}: ${response.statusText}${errorText ? ` - ${errorText}` : ''}`,
				);
			}

			const data = await response.json();
			results.push({
				conceptName: scriptData.conceptName,
				success: true,
				response: data,
			});
		} catch (error) {
			console.error(
				`Error sending script for concept "${scriptData.conceptName}":`,
				error,
			);
			results.push({
				conceptName: scriptData.conceptName,
				success: false,
				error: error instanceof Error ? error.message : 'Unknown error',
			});
		}
	}

	return results;
}
